name: build
# This workflow is triggered on pushes to the repository.
on: [push, pull_request]

jobs:
  build:
    name: build-job
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repo
      uses: actions/checkout@v2
    - name: Docker Build
      run: make build
